### ISSUE TITLE
Adjacent tiles not rendering when zoomed in

### ISSUE THREAD

**Issue by blakeedwards823** [Esri/arcgis-runtime-toolkit-java#22]
Hello! 

I am a member of a company that is a large client to ArcGIS. I am currently experiencing what seems to be a bug. When zooming into a rendered map to a high degree, the center tile in view remains rendered. However, when panning away from the currently rendered tile, the adjacent tiles do not render. Additionally, the sole rendered tile disappears once panning off of it, leaving the entire map grey. Our map needs to zoom in to a high degree (even if the map does not have tiles to render) and be able to pan while allowing adjacent tiles to render. After making a hard coded "safe zoom" level for our application that allows adjacent tiles to render while panning, our clients have came back and reported this to be unacceptable. Is there any way to fix this bug? Finally, I have looked at other examples of implementation of ArcGIS and see similar problems where developers have made finicky, hacky fixes. Helping us solve this problem would likely be of benefit to many other developers as well!

Attached are some photos for reference of what I am speaking of:
![IMG-1170](https://user-images.githubusercontent.com/49415344/59685000-2ce1b200-91a9-11e9-8b22-2aba8c9c7d34.JPG)
![IMG-1171](https://user-images.githubusercontent.com/49415344/59685002-2e12df00-91a9-11e9-8c04-0fa0d8a7631a.JPG)
![IMG-1172](https://user-images.githubusercontent.com/49415344/59685004-2f440c00-91a9-11e9-93b8-12ee871e9b3c.JPG)
![IMG-1173](https://user-images.githubusercontent.com/49415344/59685008-30753900-91a9-11e9-88fb-55ab7bb211c4.JPG)

Thanks in advance for any help.

**Comment by mbcoder** [comment]
@blakeedwards823 this isn't the best place to post this kind of question.  This is a repository used for the JavaFX toolkit.

You should put your post into one of our GetNet forums.  If you tell me a little more about the product you are using then I can point you in the right place.

 - What product are you using to develop your app?  Is it a native Runtime application was for Java, Android, iOS, .Net etc?  Or are you writing a web application using Java Script?

 - Next what version of the product are you using?

Let me know and I'll point you in the right direction.

**Comment by blakeedwards823** [comment]
Hi Mark,

Thank you for the fast response. I'd be happy to copy and move my question
to another, more appropriate, forum. We are using the ArcGIS library to
render maps on an Android device for tactical navigation purposes. This is
the version we are using from our Gradle
dependencies: com.esri.arcgis.android:arcgis-android:10.2.8-1. Please let
me know as soon as you can where to post this question. Thank you.

Best regards,
Blake Edwards

**Comment by mbcoder** [comment]
Blake,

The forum page for the ArcGIS Runtime SDK for Android is here https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android

I actually work on that team so may end up looking at this.  

One observation is that you are using a very old version of the SDK which is no longer supported.  The latest version of the product is 100.5 - you may have more luck with the latest version.

Take a look at https://developers.arcgis.com/android/latest/guide/guide.htm 

I'll close this issue for the moment.

Mark

**Comment by blakeedwards823** [comment]
Hi Mark,
I have posted my issue here and this issue can be removed or closed here on
Github. Thanks again for your help.
