### ISSUE TITLE
Can we have maven artefacts please

### ISSUE THREAD

**Issue by dwhitla** [Esri/arcgis-runtime-toolkit-java#41]
The last released maven artefact is > 3 years old - meanwhile master has moved on by > 100 commits. The great work merged to master is of little use if it is never released.

**Comment by mbcoder** [comment]
We do plan to release the toolkit at again as a maven artefact at some point in the future.  We have new toolkit components planned, but we've been concentrating on other areas of the product.

**Comment by mbcoder** [comment]
Closing this issue as we are shortly going to be releasing a new version of the toolkit which will also be published on our Maven repository.  This will be released after U14 of ArcGIS Runtime.
